language: java
sudo: required
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.m2"
install:
  - wget https://s3.eu-central-1.amazonaws.com/vatbubjdk/jdk-8u191-linux-x64.tar.gz -nv
  - tar -xf jdk-8u191-linux-x64.tar.gz
  - export JAVA_HOME=/home/travis/build/vatbub/randomusers/jdk1.8.0_191/
script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify -DtrimStackTrace=false --settings travisMavenSettings.xml
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then mvn deploy --settings travisMavenSettings.xml; fi
notifications:
  email:
    recipients:
      - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
on_failure: always